name: Run tests

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - category: Unit
            cmd: test/WorkflowCore.UnitTests
          - category: Integration
            cmd: test/WorkflowCore.IntegrationTests
          - category: MongoDB
            cmd: test/WorkflowCore.Tests.MongoDB
          - category: MySQL
            cmd: test/WorkflowCore.Tests.MySQL
          - category: PostgreSQL
            cmd: test/WorkflowCore.Tests.PostgreSQL
          - category: Redis
            cmd: test/WorkflowCore.Tests.Redis
          - category: SqlServer
            cmd: test/WorkflowCore.Tests.SqlServer
          - category: ElasticSearch
            cmd: test/WorkflowCore.Tests.Elasticsearch
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: ${{ matrix.category }} Tests
        run: dotnet test ${{ matrix.cmd }} --no-build --verbosity normal -p:ParallelizeTestCollections=false