name: Publish CVM WorkflowCore

on:
  push:
    tags:
      - "Release/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: '6.0.x'
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      ARTIFACTS_DIR: './artifacts/nuget/cvm.workflowcore'
      PROJECT_WORKFLOWCORE: 'src/WorkflowCore/WorkflowCore.csproj'
      PKG_NAME_WORKFLOWCORE: 'WorkflowCore'
      PROJECT_WORKFLOWCORE_MONGODB: 'src/providers/WorkflowCore.Persistence.MongoDB/WorkflowCore.Persistence.MongoDB.csproj'
      PKG_NAME_WORKFLOWCORE_MONGODB: 'WorkflowCore.Persistence.MongoDB'
      PROJECT_WORKFLOWCORE_DSL: 'src/WorkflowCore.DSL/WorkflowCore.DSL.csproj'
      PKG_NAME_WORKFLOWCORE_DSL: 'WorkflowCore.DSL'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/Release\//}" >> $GITHUB_OUTPUT

      - name: Restore dependencies
        run: dotnet restore

      - name: Build '${{ env.PKG_NAME_WORKFLOWCORE }}'
        run: dotnet build ${{ env.PROJECT_WORKFLOWCORE }} --configuration Release -p:Version=${{ steps.extract_version.outputs.VERSION }} --no-restore

      - name: Build '${{ env.PKG_NAME_WORKFLOWCORE_MONGODB }}'
        run: dotnet build ${{ env.PROJECT_WORKFLOWCORE_MONGODB }} --configuration Release -p:Version=${{ steps.extract_version.outputs.VERSION }} --no-restore

      - name: Build '${{ env.PKG_NAME_WORKFLOWCORE_DSL }}'
        run: dotnet build ${{ env.PROJECT_WORKFLOWCORE_DSL }} --configuration Release -p:Version=${{ steps.extract_version.outputs.VERSION }} --no-restore

      - name: Pack '${{ env.PKG_NAME_WORKFLOWCORE }}'
        run: dotnet pack ${{ env.PROJECT_WORKFLOWCORE }} --configuration Release --output ${{ env.ARTIFACTS_DIR }} -p:Version=${{ steps.extract_version.outputs.VERSION }} --no-build

      - name: Pack '${{ env.PKG_NAME_WORKFLOWCORE_MONGODB }}'
        run: dotnet pack ${{ env.PROJECT_WORKFLOWCORE_MONGODB }} --configuration Release --output ${{ env.ARTIFACTS_DIR }} -p:Version=${{ steps.extract_version.outputs.VERSION }} --no-build

      - name: Pack '${{ env.PKG_NAME_WORKFLOWCORE_DSL }}'
        run: dotnet pack ${{ env.PROJECT_WORKFLOWCORE_DSL }} --configuration Release --output ${{ env.ARTIFACTS_DIR }} -p:Version=${{ steps.extract_version.outputs.VERSION }} --no-build

      - name: Push NuGet Packages
        run: dotnet nuget push ${{ env.ARTIFACTS_DIR }}/*.nupkg --source ${{ secrets.NUGET_SOURCE }} --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate