name: Publish CVM WorkflowCore

on:
  push:
    tags:
      - "ReleaseWorkflowCorePersistenceMongoDB/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: '6.0.x'
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      ARTIFACTS_DIR: './artifacts/nuget/cvm.workflowcore'
      PROJECT: 'src/providers/WorkflowCore.Persistence.MongoDB/WorkflowCore.Persistence.MongoDB.csproj'
      PKG_NAME: 'WorkflowCore.Persistence.MongoDB'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/ReleaseWorkflowCorePersistenceMongoDB\//}" >> $GITHUB_OUTPUT

      - name: Restore dependencies
        run: dotnet restore

      - name: Build '${{ env.PKG_NAME }}'
        run: dotnet build ${{ env.PROJECT }} --configuration Release -p:Version=${{ steps.extract_version.outputs.VERSION }} --no-restore

      - name: Pack '${{ env.PKG_NAME }}'
        run: dotnet pack ${{ env.PROJECT }} --configuration Release --output ${{ env.ARTIFACTS_DIR }} -p:PackageId="Dodo.Cvm.${{ env.PKG_NAME }}" -p:Version=${{ steps.extract_version.outputs.VERSION }} --no-build

      - name: Push NuGet Packages
        run: dotnet nuget push ${{ env.ARTIFACTS_DIR }}/*.nupkg --source ${{ secrets.NUGET_SOURCE }} --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate