name: Publish CVM WorkflowCore

on:
  push:
    tags:
      - "Release/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      PROJECT_WORKFLOWCORE: 'src/WorkflowCore/WorkflowCore.csproj'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          source-url: ${{ secrets.NUGET_SOURCE }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Restore NuGet cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nugetcache-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            nugetcache-

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/Release\//}" >> $GITHUB_OUTPUT

      - name: Restore dependencies
        run: dotnet restore $PROJECT_WORKFLOWCORE

      - name: Build
        run: dotnet build $PROJECT_WORKFLOWCORE --configuration Release --no-restore

      - name: Pack
        run: dotnet pack $PROJECT_WORKFLOWCORE --configuration Release --output ./artifacts/nuget/cvm.workflowcore -p:Version=${{ steps.extract_version.outputs.VERSION }}

      - name: Push NuGet Package
        run: dotnet nuget push ./artifacts/nuget/cvm.workflowcore/*.nupkg --source ${{ secrets.NUGET_SOURCE }} --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate